apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  ports:
    - port: 8000
  selector:
    app: django
    tier: app
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-app-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: app
    spec:
      volumes:
        - name: django-app-data
          persistentVolumeClaim:
            claimName: django-app-pvc
      containers:
        - image: 945219712954.dkr.ecr.us-east-1.amazonaws.com/django-k8s-app:latest
          name: app
          ports:
            - containerPort: 8080
              name: app
          volumeMounts:
            - name: django-app-data
              mountPath: /vol/web
          env:
            - name: DB_HOST
              value: django-k8s-db.ck9uucosgv9c.us-east-1.rds.amazonaws.com
            - name: DB_NAME
              value: djangoproject
            - name: DB_USER
              value: djangouser
            - name: ALLOWED_HOSTS
              value: 'a3a0af6f1f63c40df89e56c697df7999-1593069963.us-east-1.elb.amazonaws.com'
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django
                  key: secret

        - image: 945219712954.dkr.ecr.us-east-1.amazonaws.com/django-k8s-proxy:latest
          name: proxy
          ports:
            - containerPort: 8000
              name: proxy
          volumeMounts:
            - name: django-app-data
              mountPath: /vol/web
          env:
            - name: APP_HOST
              value: '127.0.0.1'
            - name: APP_PORT
              value: '8080'
